### ISSUE TITLE
Feature request: another tape image with different tests

### ISSUE THREAD

**Issue by josedpedroso** [brendanalford/zx-diagnostics#28]
Would it be possible to build a different tape image with at least some of the tests that are not included in the current one? I understand that the tape image is loaded to RAM, so for RAM tests it's best to have a small program. However, I have a 128 I'd like to test fully, but I don't yet have any ROM accessories for it. Thanks.

**Comment by brendanalford** [comment]
The tape image is already at the limits of what can be run in the space available in lower RAM - bear in mind that 6.5K of the 16K is taken up by screen memory. I've had to remove some of the more unusual ROM checksums so it'll fit in the available space, so unfortunately this won't be feasible, sorry.

The 128 machine can take an EPROM in place of the standard ROM, so it's possible to have an EPROM burns with the full diagnostic software and replace the standard ROM with it in order to run the full suite.

**Comment by josedpedroso** [comment]
Unfortunately my 128 is a later model with no socketed ICs, but I might purchase a board with an external ROM. Thanks for your work, it is much appreciated.
