### ISSUE TITLE
Detected unrecognized ROM checksum under ZXPoly emulator in ZX128 mode

### ISSUE THREAD

**Issue by raydac** [brendanalford/zx-diagnostics#32]
ZX Diagnostics ROM checker shows such picture under [ZXPoly emulator](https://github.com/raydac/zxpoly) in ZX128 mode emulation mode. The emulator uses ROM downloaded and extracted from another emulators (selected through preferences options)
![image](https://user-images.githubusercontent.com/3008810/147339260-9720b258-9afc-4778-ab9c-b41d7e28d4e9.png)

**Comment by raydac** [comment]
also question, how do you check pressed key for the screen? may be I have some bug in my emulator but your program doesn't detect any pressed key and trying to start in ZX48 after delay
![image](https://user-images.githubusercontent.com/3008810/147351569-3c04a375-cb47-458d-9af7-6e9fac7765d1.png)

**Comment by brendanalford** [comment]
The ROM checksum works by attempting to cycle through all four possible ROM pages that are accessible on a +2A/+3. On a 128 machine this returns two distinct checksums at ROM0/ROM1 that are repeated at ROM2/ROM3.

The second checksum (BE09) is correct for a UK 128 Toastrack but the first is unrecognised, I suspect due to a potential off-by-one error in the emulator - check that it is not treating address 3FFF as RAM by mistake. 

As for the key press issue, this is the code that detects the machine type selection from the keyboard (testrommain, lines 1038-1049):

	select_test_1
	
	 ;	Read key row 1-5
	
	ld bc, 0xf7fe
	in a, (c)
	
	 ; 	Only interested in keys 1,2,3 and 4
	
	and 0xf
	cp 0xf
	jp z, select_test

	
Check that your emulation is using the full BC register pair as the I/O address when performing the `in a, (c)` instruction.

Best of luck with your emulator development!
